-- 施工人員名冊 Supabase 第一階段資料結構
-- 這份 migration 不會刪除 Google Sheets 資料；可先建立空的 Supabase 結構，再做資料比對與切換。

create extension if not exists pgcrypto;

create table if not exists public.contractors (
  id text primary key,
  name text not null check (char_length(trim(name)) between 1 and 100),
  company_type text not null default 'subcontractor'
    check (company_type in ('primary', 'subcontractor')),
  status text not null default 'active'
    check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  archived_at timestamptz
);

create unique index if not exists contractors_active_name_key
  on public.contractors (lower(trim(name)))
  where status = 'active';

create table if not exists public.workers (
  id text primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  id_number text not null check (char_length(trim(id_number)) between 8 and 10),
  phone text not null check (char_length(trim(phone)) between 7 and 30),
  emergency_contact text not null check (char_length(trim(emergency_contact)) between 1 and 60),
  emergency_phone text not null check (char_length(trim(emergency_phone)) between 7 and 30),
  blood_type text not null check (blood_type in ('A', 'B', 'AB', 'O')),
  job_title text not null check (char_length(trim(job_title)) between 1 and 80),
  contractor_id text not null references public.contractors(id),
  contractor_name text not null,
  entry_date date not null,
  notes text not null default '' check (char_length(notes) <= 500),
  photo_storage_path text,
  photo_file_id text,
  created_at timestamptz not null default now(),
  status text not null default 'active'
    check (status in ('active', 'deleted')),
  deleted_at timestamptz,
  updated_at timestamptz not null default now(),
  submission_id text not null,
  consented_at timestamptz not null,
  source text not null default 'public',
  created_by_id text not null default '',
  created_by_name text not null default ''
);

create unique index if not exists workers_submission_id_key
  on public.workers (submission_id);

create unique index if not exists workers_active_id_number_key
  on public.workers (upper(trim(id_number)))
  where status = 'active' and trim(id_number) <> '';

create unique index if not exists workers_active_profile_key
  on public.workers (contractor_id, lower(trim(name)), trim(phone))
  where status = 'active';

create index if not exists workers_active_contractor_created_key
  on public.workers (contractor_id, created_at desc)
  where status = 'active';

create table if not exists public.managers (
  id text primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  username text not null unique,
  display_name text not null,
  email text not null,
  role text not null check (role in ('owner', 'contractor')),
  contractor_id text references public.contractors(id),
  contractor_name text not null default '',
  status text not null default 'active'
    check (status in ('active', 'disabled')),
  must_change_password boolean not null default false,
  session_version text not null default gen_random_uuid()::text,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  locked_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz,
  constraint managers_role_scope_check check (
    (role = 'owner' and contractor_id is null)
    or (role = 'contractor' and contractor_id is not null)
  )
);

create unique index if not exists managers_active_contractor_key
  on public.managers (contractor_id)
  where role = 'contractor' and status = 'active';

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  actor_id text not null default '',
  actor_role text not null default '',
  actor_contractor_id text not null default '',
  action text not null,
  target_type text not null,
  target_id text not null default '',
  details text not null default ''
);

create index if not exists audit_logs_timestamp_key
  on public.audit_logs (timestamp desc);

create or replace function public.current_manager_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select m.role
  from public.managers m
  where m.auth_user_id = auth.uid()
    and m.status = 'active'
  limit 1
$$;

create or replace function public.current_manager_contractor_id()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select m.contractor_id
  from public.managers m
  where m.auth_user_id = auth.uid()
    and m.status = 'active'
  limit 1
$$;

create or replace function public.is_active_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_manager_role() = 'owner', false)
$$;

create or replace function public.get_public_contractors()
returns table (
  id text,
  name text,
  company_type text,
  level_label text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    c.id,
    c.name,
    c.company_type,
    case when c.company_type = 'primary' then '主承包商' else '次承包商' end
  from public.contractors c
  where c.status = 'active'
  order by case when c.company_type = 'primary' then 0 else 1 end, c.name;
$$;

grant execute on function public.get_public_contractors() to anon, authenticated;
grant execute on function public.current_manager_role() to authenticated;
grant execute on function public.current_manager_contractor_id() to authenticated;
grant execute on function public.is_active_owner() to authenticated;

alter table public.contractors enable row level security;
alter table public.workers enable row level security;
alter table public.managers enable row level security;
alter table public.audit_logs enable row level security;

grant select, insert, update, delete on public.contractors to authenticated;
grant select, insert, update, delete on public.workers to authenticated;
grant select, insert, update, delete on public.managers to authenticated;
grant select, insert on public.audit_logs to authenticated;

drop policy if exists contractors_manager_select on public.contractors;
create policy contractors_manager_select
  on public.contractors for select to authenticated
  using (public.is_active_owner() or id = public.current_manager_contractor_id());

drop policy if exists contractors_owner_insert on public.contractors;
create policy contractors_owner_insert
  on public.contractors for insert to authenticated
  with check (public.is_active_owner());

drop policy if exists contractors_owner_update on public.contractors;
create policy contractors_owner_update
  on public.contractors for update to authenticated
  using (public.is_active_owner())
  with check (public.is_active_owner());

drop policy if exists contractors_owner_delete on public.contractors;
create policy contractors_owner_delete
  on public.contractors for delete to authenticated
  using (public.is_active_owner());

drop policy if exists workers_manager_select on public.workers;
create policy workers_manager_select
  on public.workers for select to authenticated
  using (public.is_active_owner() or contractor_id = public.current_manager_contractor_id());

drop policy if exists workers_manager_insert on public.workers;
create policy workers_manager_insert
  on public.workers for insert to authenticated
  with check (public.is_active_owner() or contractor_id = public.current_manager_contractor_id());

drop policy if exists workers_manager_update on public.workers;
create policy workers_manager_update
  on public.workers for update to authenticated
  using (public.is_active_owner() or contractor_id = public.current_manager_contractor_id())
  with check (public.is_active_owner() or contractor_id = public.current_manager_contractor_id());

drop policy if exists workers_manager_delete on public.workers;
create policy workers_manager_delete
  on public.workers for delete to authenticated
  using (public.is_active_owner() or contractor_id = public.current_manager_contractor_id());

drop policy if exists managers_self_or_owner_select on public.managers;
create policy managers_self_or_owner_select
  on public.managers for select to authenticated
  using (public.is_active_owner() or auth_user_id = auth.uid());

drop policy if exists managers_owner_insert on public.managers;
create policy managers_owner_insert
  on public.managers for insert to authenticated
  with check (public.is_active_owner());

drop policy if exists managers_owner_update on public.managers;
create policy managers_owner_update
  on public.managers for update to authenticated
  using (public.is_active_owner() or auth_user_id = auth.uid())
  with check (public.is_active_owner() or auth_user_id = auth.uid());

drop policy if exists managers_owner_delete on public.managers;
create policy managers_owner_delete
  on public.managers for delete to authenticated
  using (public.is_active_owner());

drop policy if exists audit_manager_insert on public.audit_logs;
create policy audit_manager_insert
  on public.audit_logs for insert to authenticated
  with check (public.is_active_owner() or actor_contractor_id = public.current_manager_contractor_id());

drop policy if exists audit_owner_select on public.audit_logs;
create policy audit_owner_select
  on public.audit_logs for select to authenticated
  using (public.is_active_owner() or actor_contractor_id = public.current_manager_contractor_id());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'worker-photos',
  'worker-photos',
  false,
  8000000,
  array['image/jpeg', 'image/png']::text[]
)
on conflict (id) do update
set public = false,
    file_size_limit = 8000000,
    allowed_mime_types = array['image/jpeg', 'image/png']::text[];

drop policy if exists worker_photos_manager_select on storage.objects;
create policy worker_photos_manager_select
  on storage.objects for select to authenticated
  using (
    bucket_id = 'worker-photos'
    and (
      public.is_active_owner()
      or split_part(name, '/', 1) = public.current_manager_contractor_id()
    )
  );

drop policy if exists worker_photos_manager_insert on storage.objects;
create policy worker_photos_manager_insert
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'worker-photos'
    and (
      public.is_active_owner()
      or split_part(name, '/', 1) = public.current_manager_contractor_id()
    )
  );

drop policy if exists worker_photos_manager_update on storage.objects;
create policy worker_photos_manager_update
  on storage.objects for update to authenticated
  using (
    bucket_id = 'worker-photos'
    and (
      public.is_active_owner()
      or split_part(name, '/', 1) = public.current_manager_contractor_id()
    )
  )
  with check (
    bucket_id = 'worker-photos'
    and (
      public.is_active_owner()
      or split_part(name, '/', 1) = public.current_manager_contractor_id()
    )
  );

drop policy if exists worker_photos_manager_delete on storage.objects;
create policy worker_photos_manager_delete
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'worker-photos'
    and (
      public.is_active_owner()
      or split_part(name, '/', 1) = public.current_manager_contractor_id()
    )
  );
